# -*- coding: utf-8 -*-
"""品富餐飲 店內播放短影片 — 6 部腳本（每部 90 秒）

每個場景欄位：
  icon     Noto Emoji 碼位（畫面主圖示）
  head     大標題（畫面文字）
  points   重點字卡（最多 3 行）
  say      旁白（同時作為字幕）
  veo      給 Gemini（Veo）產生 8 秒實拍風格畫面的英文提示詞
"""

STYLE = ("Cinematic 16:9, soft natural lighting, clean modern Taiwanese food-service kitchen, "
         "warm and trustworthy mood, shallow depth of field, slow smooth camera movement, "
         "no on-screen text, no logos, no brand names.")

VIDEOS = [
    {
        "id": "01", "slug": "brand", "title": "每一餐，都安心", "series": "品牌形象",
        "audience": "所有來客", "voice": "zh-TW-HsiaoChenNeural",
        "c1": (20, 44, 82), "c2": (14, 110, 110), "accent": (255, 196, 87),
        "scenes": [
            {"icon": "1f37d", "head": "歡迎來到品富餐飲", "points": ["90 秒，認識我們", "怎麼準備你的每一餐"],
             "say": "你好，歡迎來到品富餐飲。用九十秒，認識我們怎麼準備你的每一餐。",
             "veo": "Wide establishing shot of a bright, spotless food counter in a hospital food court at lunchtime, staff in white uniforms and hairnets smiling and serving customers."},
            {"icon": "1f3e5", "head": "我們在你身邊", "points": ["醫院", "科技園區", "每天忙碌的你"],
             "say": "品富在醫院、科技園區設櫃，服務每天忙碌的醫護人員、工程師，和每一位朋友。",
             "veo": "Montage feel: a nurse and an engineer in a cleanroom-style jacket each picking up a lunch box from a counter, friendly handover, natural daylight."},
            {"icon": "1f331", "head": "好餐點的起點", "points": ["新鮮食材", "確實的流程"],
             "say": "我們相信，一份好的餐點，從新鮮的食材開始，也從確實的流程開始。",
             "veo": "Close-up of fresh vegetables, eggs and chicken being placed on a stainless steel prep table, droplets of water, morning light."},
            {"icon": "1f69a", "head": "收貨把關", "points": ["檢查外觀", "量測溫度", "確認有效日期"],
             "say": "每一批食材進到廚房，都要先檢查外觀、溫度與有效日期，合格才能入庫。",
             "veo": "A kitchen staff member with gloves checking a delivery box, using a probe thermometer on chilled meat and reading the date on the package."},
            {"icon": "1f9ca", "head": "分區保存", "points": ["冷凍 ・ 冷藏", "乾貨 ・ 蔬菜", "避免交叉污染"],
             "say": "冷凍、冷藏、乾貨和蔬菜分區存放，各自有固定位置，避免交叉污染。",
             "veo": "Slow pan across an organized walk-in refrigerator with labeled shelves and neatly stacked containers, cool blue light."},
            {"icon": "1f3f7", "head": "清楚標示", "points": ["品名 ・ 原包裝有效日", "分裝日期 ・ 櫃位使用期限"],
             "say": "分裝後的食材，都會貼上品保標籤，寫清楚品名、原包裝有效日、分裝日期和櫃位使用期限。",
             "veo": "Macro shot of a gloved hand sticking a small white food label onto a sealed food container on a steel counter."},
            {"icon": "1f5a8", "head": "智慧升級中", "points": ["系統計算日期", "自動列印標籤", "減少手寫錯誤"],
             "say": "我們正在導入智慧品保標籤系統，由系統計算並列印日期，減少手寫錯誤。",
             "veo": "A staff member tapping a rugged touchscreen terminal in a kitchen, a compact thermal label printer next to it printing a label."},
            {"icon": "1f373", "head": "用心烹調", "points": ["標準作業流程", "味道與份量穩定一致"],
             "say": "廚房夥伴依照標準流程烹調，讓每一份餐點的味道與份量都穩定一致。",
             "veo": "Chef stir-frying vegetables in a wok with a gentle flame, steam rising, then plating rice and side dishes into a lunch box."},
            {"icon": "1f4ac", "head": "我們想聽你說", "points": ["有任何建議", "歡迎告訴現場夥伴"],
             "say": "對餐點有任何建議，歡迎告訴現場夥伴，我們會持續改進。",
             "veo": "A customer chatting warmly with a counter staff member who nods and listens attentively, soft background bokeh."},
            {"icon": "1f496", "head": "品富餐飲", "points": ["每一餐，都安心", "謝謝你的光臨"],
             "say": "品富餐飲，每一餐，都安心。謝謝你的光臨。",
             "veo": "Slow push-in on a beautifully plated Taiwanese bento box on a wooden table, warm golden light, steam gently rising."},
        ],
    },
    {
        "id": "02", "slug": "smart-label", "title": "看得懂的安心", "series": "智慧品保標籤",
        "audience": "所有來客（食安信任）", "voice": "zh-TW-HsiaoChenNeural",
        "c1": (16, 52, 74), "c2": (36, 120, 96), "accent": (126, 232, 190),
        "scenes": [
            {"icon": "1f50d", "head": "廚房裡的小標籤", "points": ["每份分裝食材", "都貼著一張品保標籤"],
             "say": "廚房裡每一份分裝好的食材，都貼著一張品保標籤。今天帶你看懂它。",
             "veo": "Macro close-up of rows of sealed food containers in a fridge, each with a small white label, camera slowly sliding along."},
            {"icon": "1f96c", "head": "第 1 欄：品名", "points": ["這是什麼食材", "一眼就看清楚"],
             "say": "第一欄是品名，告訴大家這是什麼食材，一眼就能看清楚。",
             "veo": "Close-up of a container of fresh shredded cabbage on a steel counter, a gloved hand pointing at its label."},
            {"icon": "1f4e6", "head": "第 2 欄：原包裝有效日", "points": ["供應商原本標示的期限", "第一效期"],
             "say": "第二欄是原包裝有效日，也就是供應商在原包裝上標示的期限。",
             "veo": "Close-up of an unopened supplier food package, a finger tracing the printed expiry date area, shallow focus."},
            {"icon": "2702", "head": "第 3 欄：分裝日期", "points": ["大包裝拆開分裝的那一刻", "就要記錄下來"],
             "say": "第三欄是分裝日期。大包裝食材拆開分裝的那一刻，就要記錄下來。",
             "veo": "Gloved hands opening a large food package and portioning it into smaller containers on a sanitized cutting board."},
            {"icon": "23f0", "head": "第 4 欄：櫃位使用期限", "points": ["在廚房裡", "可以使用的最後時間"],
             "say": "第四欄是櫃位使用期限，代表食材在廚房裡可以使用的最後時間。",
             "veo": "A wall clock in a clean kitchen with a soft focus pull to a labeled container below it."},
            {"icon": "1f6ab", "head": "鐵則：只能縮短，不能延長", "points": ["櫃位使用期限 ≤ 原包裝有效日", "分裝・解凍・補印 都不延長"],
             "say": "最重要的鐵則：櫃位使用期限，不能晚於原包裝有效日。分裝、解凍、補印，都不能讓期限變長。",
             "veo": "Dramatic but clean shot of a supervisor in a kitchen reviewing a checklist on a clipboard, firm and focused expression."},
            {"icon": "270d", "head": "過去：人工手寫", "points": ["手寫日期、心算期限", "忙碌時難免出錯"],
             "say": "過去，這些日期靠人工手寫、心算，尖峰時段難免出錯。",
             "veo": "Busy kitchen at peak hour, a staff member hurriedly handwriting on a small label with a marker, slightly hectic atmosphere."},
            {"icon": "1f5a8", "head": "導入後：系統自動計算", "points": ["選擇食材", "依核准規則算日期", "自動列印"],
             "say": "導入智慧品保標籤後，夥伴只要選擇食材，系統就依主管核准的規則計算日期，自動列印。",
             "veo": "Calm kitchen, a staff member selects an item on a touchscreen and a thermal printer smoothly prints a label, satisfying moment."},
            {"icon": "1f517", "head": "每張標籤都能追溯", "points": ["批次編號", "可追查到原供應商批次"],
             "say": "每張標籤都有批次編號，必要時能追查到原本的供應商批次。",
             "veo": "Close-up of a label with a small QR code being scanned by a handheld scanner, soft green light reflection."},
            {"icon": "2705", "head": "看得懂的標籤", "points": ["吃得到的安心", "品富餐飲"],
             "say": "看得懂的標籤，吃得到的安心。品富餐飲，守護你的每一餐。",
             "veo": "Final hero shot: a neatly labeled food container next to a finished meal box, warm light, camera slowly pulls back."},
        ],
    },
    {
        "id": "03", "slug": "food-journey", "title": "食材的旅程", "series": "從收貨到你的餐盤",
        "audience": "所有來客", "voice": "zh-TW-YunJheNeural",
        "c1": (66, 38, 24), "c2": (150, 84, 36), "accent": (255, 214, 140),
        "scenes": [
            {"icon": "1f5fa", "head": "食材的旅程", "points": ["一份餐點上桌前", "食材走過哪些路？"],
             "say": "一份餐點來到你手上之前，食材走過哪些路？一起來看看。",
             "veo": "Aerial-feel shot of a refrigerated delivery truck arriving at a loading area in early morning light."},
            {"icon": "1f69a", "head": "第 1 站：收貨驗收", "points": ["包裝完整", "溫度正確", "有效日期足夠"],
             "say": "第一站，收貨驗收。檢查包裝、溫度，和有效日期。",
             "veo": "Staff in uniform receiving boxes from a delivery driver and checking items against a list on a clipboard."},
            {"icon": "1f9ca", "head": "第 2 站：冷鏈入庫", "points": ["冷藏 7°C 以下", "冷凍 −18°C 以下"],
             "say": "第二站，冷鏈入庫。冷藏保存在攝氏七度以下，冷凍保存在攝氏零下十八度以下。",
             "veo": "Close-up of a digital thermometer display on a walk-in freezer door, then the door opens revealing frosty organized shelves."},
            {"icon": "1f504", "head": "第 3 站：先進先出", "points": ["先到期的先使用", "減少過期浪費"],
             "say": "第三站，先進先出。先到期的食材先使用，減少過期造成的浪費。",
             "veo": "Staff rotating stock on a shelf, moving older containers to the front and placing new ones at the back."},
            {"icon": "1f3f7", "head": "第 4 站：分裝標示", "points": ["分成適當份量", "貼上品保標籤"],
             "say": "第四站，分裝標示。食材分成適當份量，貼上品保標籤，清楚記錄日期。",
             "veo": "Gloved hands portioning sliced chicken into containers and applying printed labels, clean steel surface."},
            {"icon": "2744", "head": "第 5 站：正確解凍", "points": ["冷藏庫中慢慢解凍", "不在室溫長時間放置"],
             "say": "第五站，解凍。食材放在冷藏庫中慢慢解凍，不在室溫下長時間放置。",
             "veo": "Time-lapse style shot of frozen fish fillets in a tray inside a refrigerator gradually thawing, soft cool light."},
            {"icon": "1f52a", "head": "第 6 站：生熟分開", "points": ["不同砧板與器具", "熟食確實加熱"],
             "say": "第六站，烹調。生食和熟食使用不同的砧板與器具，熟食一定確實加熱。",
             "veo": "Color-coded cutting boards on a counter, a chef using a red board for raw meat and a green board for vegetables."},
            {"icon": "1f525", "head": "第 7 站：保溫出餐", "points": ["熱食保持 60°C 以上", "冷食保持冷藏"],
             "say": "第七站，出餐。熱食保溫在攝氏六十度以上，冷食維持冷藏。",
             "veo": "Steam table with hot dishes in stainless pans, a server ladling food into a bento box, steam rising."},
            {"icon": "1f371", "head": "終點：你的餐盤", "points": ["每一站都用心", "才有這一份安心"],
             "say": "最後一站，就是你的餐盤。每一站都用心，才有這一份安心。",
             "veo": "A customer opening a fresh bento box at a table and smiling, natural window light."},
            {"icon": "1f496", "head": "品富餐飲", "points": ["從收貨到餐桌", "每一步都認真把關"],
             "say": "品富餐飲，從收貨到餐桌，每一步都認真把關。",
             "veo": "Slow-motion shot of fresh ingredients arranged in a circle on a wooden board, camera rotating gently above."},
        ],
    },
    {
        "id": "04", "slug": "my-plate", "title": "我的餐盤 六口訣", "series": "均衡飲食",
        "audience": "所有來客（健康衛教）", "voice": "zh-TW-HsiaoChenNeural",
        "c1": (24, 70, 48), "c2": (96, 148, 60), "accent": (255, 230, 120),
        "scenes": [
            {"icon": "1f957", "head": "吃得均衡，其實很簡單", "points": ["國民健康署「我的餐盤」", "六句口訣記起來"],
             "say": "吃得均衡很簡單。國民健康署的「我的餐盤」，用六句口訣幫你記住。",
             "veo": "Top-down shot of a round plate divided into sections with rice, vegetables, fruit, tofu and fish, bright natural light."},
            {"icon": "1f95b", "head": "每天早晚一杯奶", "points": ["每天 1.5～2 杯乳品", "1 杯約 240 毫升"],
             "say": "第一句，每天早晚一杯奶。每天一杯半到兩杯乳品，一杯約兩百四十毫升。",
             "veo": "A glass of milk being poured on a breakfast table in soft morning light, slow motion."},
            {"icon": "1f34e", "head": "每餐水果拳頭大", "points": ["每餐一個拳頭大小", "選當季、多樣化"],
             "say": "第二句，每餐水果拳頭大，選擇當季、多樣化。",
             "veo": "A hand holding a fresh guava next to a fist-sized portion of cut fruit in a small bowl, colorful and fresh."},
            {"icon": "1f966", "head": "菜比水果多一點", "points": ["蔬菜份量比水果多", "深色蔬菜 1/3 以上"],
             "say": "第三句，菜比水果多一點，深色蔬菜最好佔三分之一以上。",
             "veo": "Close-up of stir-fried leafy greens and broccoli in a bowl, vibrant green, steam rising."},
            {"icon": "1f35a", "head": "飯跟蔬菜一樣多", "points": ["全穀雜糧 ≈ 蔬菜份量", "1/3 以上選未精製全穀"],
             "say": "第四句，飯跟蔬菜一樣多，其中三分之一以上，選擇糙米、燕麥等未精製全穀。",
             "veo": "Side-by-side bowls of brown rice and mixed vegetables of equal size on a table, gentle camera slide."},
            {"icon": "1f41f", "head": "豆魚蛋肉一掌心", "points": ["每餐約一個掌心大小", "優先：豆 → 魚 → 蛋 → 肉"],
             "say": "第五句，豆魚蛋肉一掌心。優先選豆類，其次是魚和海鮮，再來是蛋，最後才是肉類。",
             "veo": "An open palm next to a palm-sized piece of grilled fish and a block of tofu on a plate, clean composition."},
            {"icon": "1f95c", "head": "堅果種子一茶匙", "points": ["每餐約 1 茶匙", "一天約 1 份，如杏仁果 5 粒"],
             "say": "第六句，堅果種子一茶匙。一天約一份，例如五粒杏仁果。",
             "veo": "Macro shot of a teaspoon of mixed nuts and seeds being sprinkled over a salad."},
            {"icon": "1f4a1", "head": "選餐小技巧", "points": ["多一份蔬菜", "少一點含糖飲料"],
             "say": "選餐時多一份蔬菜、少一點含糖飲料，就是好的開始。",
             "veo": "A person at a food counter choosing an extra vegetable side dish and a bottle of water instead of soda."},
            {"icon": "1f4da", "head": "資料來源", "points": ["衛生福利部國民健康署「我的餐盤」", "特殊需求請諮詢營養師或醫師"],
             "say": "資料來源：國民健康署。有特殊健康需求，請諮詢營養師或醫師。",
             "veo": "Friendly dietitian in a white coat explaining a healthy plate model to a visitor in a bright clinic room."},
            {"icon": "1f496", "head": "品富餐飲", "points": ["均衡吃", "每一餐都有好心情"],
             "say": "品富餐飲，陪你均衡吃，每一餐都有好心情。",
             "veo": "Group of coworkers sharing a balanced lunch together and laughing in a sunny break room."},
        ],
    },
    {
        "id": "05", "slug": "save-food", "title": "惜食減廢", "series": "一起珍惜每一口",
        "audience": "所有來客（環保永續）", "voice": "zh-TW-YunJheNeural",
        "c1": (20, 60, 66), "c2": (70, 130, 90), "accent": (190, 240, 140),
        "scenes": [
            {"icon": "1f30f", "head": "珍惜每一口", "points": ["減少浪費", "從一餐飯開始"],
             "say": "減少食物浪費，不需要很困難。從眼前這一餐飯開始，我們就能一起做到。",
             "veo": "Gentle shot of a clean empty plate with chopsticks resting on it after a finished meal, warm light."},
            {"icon": "1f914", "head": "吃多少，點多少", "points": ["點餐前", "先想想自己的食量"],
             "say": "第一個習慣，吃多少，點多少。點餐前，先想想自己今天的食量。",
             "veo": "A customer thoughtfully looking at a menu board at a food counter, pondering, natural light."},
            {"icon": "1f961", "head": "吃不完，打包帶走", "points": ["打包回家", "兩小時內冷藏"],
             "say": "第二個習慣，吃不完就打包帶走，記得在兩小時內放進冰箱冷藏。",
             "veo": "Hands packing leftover food neatly into a reusable container and closing the lid."},
            {"icon": "1f964", "head": "自備餐具與環保杯", "points": ["少用一次性用品", "外帶也能很環保"],
             "say": "第三個習慣，外帶時自備餐具和環保杯，少用一次性用品。",
             "veo": "A person pulling a reusable cutlery set and a stainless tumbler from a tote bag at a takeaway counter."},
            {"icon": "267b", "head": "做好分類回收", "points": ["依現場標示", "廚餘・回收・一般垃圾"],
             "say": "第四個習慣，用完餐後，請依照現場標示，把廚餘、資源回收和一般垃圾分開。",
             "veo": "Clean sorting station with three bins, a person dropping a paper cup into the recycling bin."},
            {"icon": "1f9d1-200d-1f373", "head": "廚房端：我們這樣做", "points": ["先進先出", "精準分裝", "期限管理"],
             "say": "在廚房裡，我們也用先進先出、精準分裝和期限管理，減少食材因為過期而被丟棄。",
             "veo": "Kitchen staff organizing ingredients by date on shelves, measured portions in containers, orderly and calm."},
            {"icon": "1f514", "head": "智慧提醒", "points": ["即將到期 提早提醒", "在期限內妥善使用"],
             "say": "導入智慧品保標籤後，即將到期的食材可以更早被提醒，讓食材在期限內被妥善使用。",
             "veo": "A touchscreen terminal in a kitchen showing a gentle alert glow, staff member checking and nodding."},
            {"icon": "1f91d", "head": "每個人少浪費一點", "points": ["累積起來", "就是很大的改變"],
             "say": "每個人少浪費一點點，累積起來，就是很大的改變。",
             "veo": "Montage of many different hands each placing a reusable cup on a long table, uplifting mood."},
            {"icon": "1f343", "head": "一起做到", "points": ["吃多少點多少", "打包・自備・分類"],
             "say": "吃多少點多少，吃不完打包，自備餐具，做好分類。四個小習慣，一起做到。",
             "veo": "Sunlit green leaves gently moving in the breeze with soft bokeh, calm and hopeful."},
            {"icon": "1f496", "head": "品富餐飲", "points": ["珍惜每一口", "謝謝你一起行動"],
             "say": "品富餐飲，珍惜每一口，謝謝你和我們一起行動。",
             "veo": "Warm final shot of a smiling counter staff member handing a meal to a customer who holds a reusable bag."},
        ],
    },
    {
        "id": "06", "slug": "takeaway-safety", "title": "外帶安心小撇步", "series": "食品保存",
        "audience": "外帶客、辦公室用餐者", "voice": "zh-TW-HsiaoChenNeural",
        "c1": (60, 30, 70), "c2": (40, 90, 140), "accent": (255, 170, 190),
        "scenes": [
            {"icon": "1f6cd", "head": "外帶餐點怎麼保存？", "points": ["帶回家、帶回辦公室", "記住這幾個重點"],
             "say": "外帶餐點怎麼保存最安心？記住這幾個重點。",
             "veo": "Office worker carrying a takeaway bag through a bright office lobby, walking toward the camera."},
            {"icon": "23f1", "head": "儘快食用", "points": ["室溫下", "不要超過 2 小時"],
             "say": "第一，熟食最好儘快食用，在室溫下放置，不要超過兩小時。",
             "veo": "Close-up of a takeaway meal box on an office desk next to a desk clock, soft afternoon light."},
            {"icon": "1f321", "head": "天氣炎熱更要注意", "points": ["超過 32°C 時", "室溫放置不超過 1 小時"],
             "say": "第二，天氣炎熱、氣溫超過攝氏三十二度時，室溫放置不要超過一小時。",
             "veo": "Hot summer street scene with heat shimmer, a person holding a takeaway bag under bright sun."},
            {"icon": "1f9ca", "head": "冷藏 7°C 以下", "points": ["暫時吃不完", "儘快放進冰箱"],
             "say": "第三，暫時吃不完的餐點，請儘快放進攝氏七度以下的冰箱冷藏。",
             "veo": "Hand placing a sealed food container into a clean home refrigerator, fridge light on."},
            {"icon": "1f4e6", "head": "分小份、用淺盒", "points": ["大份量分裝", "降溫更快"],
             "say": "第四，大份量的食物，分成小份、裝在淺的盒子裡，降溫會更快。",
             "veo": "Portioning a large amount of food into several shallow glass containers on a kitchen counter."},
            {"icon": "1f525", "head": "復熱要熱透", "points": ["中心溫度 74°C 以上", "整份均勻熱透"],
             "say": "第五，再次食用前要徹底加熱，讓中心溫度達到攝氏七十四度以上，整份均勻熱透。",
             "veo": "Food thermometer inserted into the center of a steaming reheated dish, digital display glowing."},
            {"icon": "261d", "head": "只復熱一次", "points": ["復熱後一次吃完", "不要反覆加熱"],
             "say": "第六，復熱過的食物，建議一次吃完，不要反覆冷藏、反覆加熱。",
             "veo": "A person enjoying a freshly reheated meal at a dining table, finishing the bowl."},
            {"icon": "1f9fa", "head": "生熟分開放", "points": ["生食放下層", "熟食放上層"],
             "say": "第七，冰箱裡生食放下層、熟食放上層，避免生食汁液滴到熟食上。",
             "veo": "Organized refrigerator interior: cooked food containers on upper shelf, raw meat in a sealed tray on the bottom shelf."},
            {"icon": "26a0", "head": "有疑慮，就別吃", "points": ["異味・變色・黏液", "請不要食用"],
             "say": "最後，食物如果有異味、變色或黏液，請不要食用。資料參考食藥署與美國農業部。",
             "veo": "Person sniffing a food container with a doubtful expression and then closing the lid, neutral kitchen."},
            {"icon": "1f496", "head": "品富餐飲", "points": ["安心帶走", "美味不減"],
             "say": "安心帶走，美味不減。品富餐飲提醒你，好好吃飯。",
             "veo": "Warm closing shot of a takeaway bag with a meal box being handed over at a counter with a smile."},
        ],
    },
]
